version: '3'

services:
  test-111:
    image: local/111-tests:${BUILD_TAG}
    command: ./gradlew -i --build-cache integrationTest
    environment:
      - PEM111_AMQP_BROKER=amqp://activemq:5672
      - PEM111_SOAP_VALIDATION_ENABLED=false
    networks:
      - 111network

  integration-adaptor-111:
    image: local/111-adapter:latest
    ports:
      - "10001:8080"
    environment:
      - PEM111_AMQP_BROKER=amqp://activemq:5672
      - PEM111_SOAP_SEND_TO=http://127.0.0.1:10001/report
      - PEM111_ITK_EXTERNAL_CONFIGURATION_URL=http://wiremock:8080/configuration/ods-dos
      - LOG_LEVEL=DEBUG
      - PEM111_SOAP_VALIDATION_ENABLED=true
    depends_on:
      - activemq
      - wiremock
    networks:
      - 111network

  nginx:
    image: local/111-nginx:latest
    ports: 
      - "8443:443"
      - "8480:80"
    networks:
      - 111network
    links:
      - "integration-adaptor-111:adapter"
    depends_on: 
      - integration-adaptor-111
      - crl-server
    environment:
      - NGINX_ADAPTER_HOSTNAME=adapter
      - NGINX_ADAPTER_PORT=8080
      - NGINX_PUBLIC_CERT
      - NGINX_PRIVATE_CERT
      - NGINX_CLIENT_PUBLIC_CERT
      - NGINX_CA_CERT
      - NGINX_CRL
      - NGINX_CRL_URL
      - DEBUG=true
      - RUN_IN_DOCKER=true
      - SERVICE_HEALTHCHECK=/actuator/health

  crl-server:
    image: local/111-crl:latest
    ports:
      - "8580:3000"
    networks:
      - 111network

  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - "8161:8161"
      - "5672:5672"
    networks:
      - 111network

  wiremock:
    build: ./wiremock
    ports:
      - "8110:8080"
    command:
      - -global-response-templating
    networks:
      - 111network
networks:
  111network:


    # - NGINX_PUBLIC_CERT="${NGINX_PUBLIC_CERT}"
    # - NGINX_PRIVATE_CERT="${NGINX_PRIVATE_CERT}"
    # - NGINX_CLIENT_PUBLIC_CERT="${NGINX_CLIENT_PUBLIC_CERT}"
    # - NGINX_CA_CERT="${NGINX_CA_CERT}"