version: '3'

services:
  integration-adaptor-111:
    image: nhsdev/nia-111-adaptor:1.0.2
    ports:
      - "8080:8080"
    environment:
      - PEM111_AMQP_BROKER=amqp://activemq:5672
      - LOG_LEVEL=DEBUG
      - PEM111_SOAP_SEND_TO
      - PEM111_SOAP_VALIDATION_ENABLED
      - PEM111_ITK_ODS_CODE_LIST=EM396
      - PEM111_ITK_DOS_ID_LIST
      - PEM111_ITK_EXTERNAL_CONFIGURATION_URL=
      - PEM111_ITK_FETCH_INTERVAL_MIN
      - PEM111_VERSION=1.0.0

  nginx:
    image: nhsdev/nia-111-nginx-adaptor:1.0.2
    ports:
      - "8443:443"
      - "8480:80"
    links:
      - "integration-adaptor-111:adapter"
    depends_on:
      - integration-adaptor-111
    environment:
      - NGINX_ADAPTER_HOSTNAME=adapter
      - NGINX_ADAPTER_PORT=8080
      - NGINX_PUBLIC_CERT
      - NGINX_PRIVATE_CERT
      - NGINX_CLIENT_PUBLIC_CERT
      - NGINX_CA_CERT
      - NGINX_CRL
      - NGINX_CRL_URL
      - DEBUG=true
      - RUN_IN_DOCKER=true
      - SERVICE_HEALTHCHECK=/actuator/health

  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - "8161:8161"
      - "5672:5672"
